name: autorun

on:
  workflow_dispatch:
  schedule:
    - cron: '0/5 * * * *'  # 每5分钟运行一次

jobs:
  check-and-restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check SOCKS5 connectivity and restart service if disconnected
        run: |
          TARGET_URL="http://ip.sb"

          if ! curl --socks5 ${{ secrets.SOCKS5_PROXY }} --connect-timeout 10 -I $TARGET_URL > /dev/null 2>&1; then
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER_HOST }} "/home/$(echo ${{ secrets.SSH_USER_HOST }} | cut -d'@' -f1)/run.sh"
          fi
