name: autorun

on:
  workflow_dispatch:
  schedule:
    - cron: '0/5 * * * *'  # 每5分钟运行一次

jobs:
  ssh-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check if service is running
        id: check_service
        run: |
          if curl --head --silent --fail ${{ secrets.WEB_SERVICE_URL }} > /dev/null; then
            echo "SERVICE_STATUS=running" >> $GITHUB_ENV
          else
            echo "SERVICE_STATUS=not_running" >> $GITHUB_ENV
          fi

      - name: Extract username and host, and run script if service is not running
        if: env.SERVICE_STATUS == 'not_running'
        run: |
          SSH_USER_HOST="${{ secrets.SSH_USER_HOST }}"
          USERNAME=$(echo "$SSH_USER_HOST" | cut -d'@' -f1)
          HOST=$(echo "$SSH_USER_HOST" | cut -d'@' -f2)
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "/home/$USERNAME/run.sh"
        # 从 SSH_USER_HOST 中提取用户名和主机名，直接在同一步骤中执行远程脚本
